name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  intl: ^0.19.0
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
